//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDetail
    {
        public int AppointmentDetailId { get; set; }
        public int AppointmentId { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string DoctorNote { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
