//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogId { get; set; }
        public string BlogTitle { get; set; }
        public string BlogSubtitle { get; set; }
        public string BlogContent { get; set; }
        public string BlogWriter { get; set; }
        public string WriterProfile { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
    }
}
