//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medinova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int MediaId { get; set; }
        public string MediaName { get; set; }
        public string MediaUrl { get; set; }
        public string MediaIcon { get; set; }
    }
}
